name: Code quality

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Setup Biome
        uses: biomejs/setup-biome@latest
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
